### PR TITLE
new floatUV for scale_inputs, clamp_float now int instead of bool, new yrange_max, yrange_half and yrange_min

### PR DESCRIPTION
**Pull request by realfinder**

### CODE REVIEW

**Comment by pinterf** [comment]
Making clamp_float as int instead of bool: doesn't it break all scripts which were already using this parameter? If so, it's a no-go. Neither here nor at a possible Avisynth Expr update.

**Comment by realfinder** [comment]
> 
> 
> Making clamp_float as int instead of bool: doesn't it break all scripts which were already using this parameter? If so, it's a no-go. Neither here nor at a possible Avisynth Expr update.

it will break them but it's not a problem since I will update all scripts after that, most if not all avs scripts updates done by me anyway

**Comment by realfinder** [comment]
and if you still care for not breaking scripts then new bool clamp_float_stuv or something is needed, when it's true (default) will be standard clamp, and when it's false will mean chroma UV clamp same as luma 0..1
and of course clamp_float_stuv will do nothing if clamp_float=false

feel free to chose the appropriate names of parameters :)

**Comment by pinterf** [comment]
O.K. I'm merging and look into what I can do with the names. When we speak about compatibility and whether it breaks something or not: we cannot assume that everybody is following your doom9 page for scripts or git, sometimes even myself have problems on fonding the latest version of your scripts. Then there is a case when someone is using a ready-to-use framework where plugins/script are bundled and just looks into new versions of some key plugins. And we cannot forget those silent ones who are just using and writing masktools and Avisynth+ on their own.

**Comment by pinterf** [comment]
(info: though it is not written, project is using spaces instead of tab characters in the source code)

**Comment by realfinder** [comment]
This explain why my changes was odd when I upload them in github

**Comment by pinterf** [comment]
Status: I'm working on the avs+ side, probably I'll put back the type-changed parameter to bool and introduce a new one.

**Comment by realfinder** [comment]
that good

after thinking, yes it's better to keep it bool not only for people who don't update but also for testing with older avs+/masktools easily

**Comment by realfinder** [comment]
so, for now, what left for this updates? put back the type-changed parameter of clamp_float to bool and introduce a new one like [clamp_float_stuv](https://github.com/pinterf/masktools/pull/6#issuecomment-554719926)? and then port all that to avs+ expr?

**Comment by pinterf** [comment]
Yes, my Expr modification is now using a new bool parameter called clamp_float_uv. So now it's a bit ahead of masktools
`{ "Expr", BUILTIN_FUNC_PREFIX, "c+s+[format]s[optAvx2]b[optSingleMode]b[optSSE2]b[scale_inputs]s[clamp_float]b[clamp_float_UV]b", Exprfilter::Create },`

**Pull request merged**
